apiVersion: v2
appVersion: 4
description: Quobyte Client Helm Chart Deployment
name: quobyte-client
version: 0.3.0
kubeVersion: "1.20-0 - 1.34-0"
type: application
icon: https://quobyte.github.io/quobyte-k8s-resources/images/quobyte.png 
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: quobyte-client
  catalog.cattle.io/display-name: Quobyte Client Deployment
keywords:
- quobyte
- storage
- client 
- pvc
- pv
- mount 
sources: 
- https://github.com/quobyte/quobyte-k8s-resources

