apiVersion: v2
appVersion: 3
description: Quobyte Cluster Helm Chart Deployment
name: quobyte-cluster
version: "0.1.6" 
kubeVersion: "1.20-0 - 1.24-0"
type: application
icon: https://quobyte.github.io/quobyte-k8s-resources/images/quobyte.png 
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: quobyte-cluster
  catalog.cattle.io/display-name: Quobyte Cluster Deployment
keywords:
- quobyte
- storage
sources: 
- https://github.com/quobyte/quobyte-k8s-resources
home: https://www.quobyte.com
